// <auto-generated />
using System;
using GZCTF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GZCTF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250901030321_AddSubmissionLimitFeature")]
    partial class AddSubmissionLimitFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is a simplified Designer file for the consolidated migration
            // The complete model is defined in AppDbContextModelSnapshot.cs
        }
    }
}