// <auto-generated />
using System;
using GZCTF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GZCTF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820002637_AddCyctfExtensions2")]
    partial class AddCyctfExtensions2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("GZCTF.Models.Data.ApiToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasComment("The unique identifier for the token.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("The timestamp when the token was created.");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("TEXT")
                        .HasComment("The ID of the user who created the token.");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasComment("The timestamp when the token expires. A null value means it never expires.");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER")
                        .HasComment("Indicates whether the token has been revoked.");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("TEXT")
                        .HasComment("The timestamp when the token was last used.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasComment("A user-friendly name for the token.");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("ApiTokens", t =>
                        {
                            t.HasComment("Stores API tokens for programmatic access.");
                        });
                });

            modelBuilder.Entity("GZCTF.Models.Data.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocalFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteUrl")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocalFileId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("GZCTF.Models.Data.CheatInfo", b =>
                {
                    b.Property<int>("SubmissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubmitTeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SubmissionId");

                    b.HasIndex("GameId");

                    b.HasIndex("SourceTeamId");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.HasIndex("SubmitTeamId");

                    b.ToTable("CheatInfo");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Config", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("ConfigKey");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Container", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExerciseInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ExpectStopAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GameInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProxy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicIP")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PublicPort")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseInstanceId")
                        .IsUnique();

                    b.HasIndex("GameInstanceId")
                        .IsUnique();

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Cyctf.Award", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Awards");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Cyctf.DivisionExtension", b =>
                {
                    b.Property<int>("DivisionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxTeamSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinTeamSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegistrationFields")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("DivisionId");

                    b.HasIndex("DivisionId");

                    b.ToTable("DivisionExtensions");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Cyctf.GameExtension", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentTeams")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailWhitelist")
                        .HasColumnType("text");

                    b.Property<int?>("MaxTeams")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("RegistrationEndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RegistrationStartTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowEventTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowRegistrationCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.HasIndex("GameId");

                    b.ToTable("GameExtensions");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Cyctf.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DivisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FormData")
                        .HasColumnType("text");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("GameId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("TeamId");

                    b.HasIndex("GameId", "TeamId", "DivisionId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Cyctf.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeLabel")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultPermissions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(31)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("GZCTF.Models.Data.DivisionChallengeConfig", b =>
                {
                    b.Property<int>("ChallengeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DivisionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Permissions")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChallengeId", "DivisionId");

                    b.HasIndex("DivisionId");

                    b.ToTable("DivisionChallengeConfig");
                });

            modelBuilder.Entity("GZCTF.Models.Data.ExerciseChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AttachmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CPUCount")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Credit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DeadlineUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExposePort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagTemplate")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hints")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MemoryLimit")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("NetworkMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0);

                    b.Property<int?>("StorageLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubmissionLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TestContainerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("TestContainerId");

                    b.ToTable("ExerciseChallenges");
                });

            modelBuilder.Entity("GZCTF.Models.Data.ExerciseDependency", b =>
                {
                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SourceId", "TargetId");

                    b.HasIndex("SourceId");

                    b.HasIndex("TargetId");

                    b.ToTable("ExerciseDependencies");
                });

            modelBuilder.Entity("GZCTF.Models.Data.ExerciseInstance", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ContainerId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FlagId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLoaded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastContainerOperation")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SolveTimeUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "ExerciseId");

                    b.HasIndex("ContainerId")
                        .IsUnique();

                    b.HasIndex("ExerciseId");

                    b.HasIndex("FlagId");

                    b.HasIndex("UserId");

                    b.ToTable("ExerciseInstances");
                });

            modelBuilder.Entity("GZCTF.Models.Data.FirstSolve", b =>
                {
                    b.Property<int>("ParticipationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChallengeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParticipationId", "ChallengeId");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.ToTable("FirstSolves");
                });

            modelBuilder.Entity("GZCTF.Models.Data.FlagContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AttachmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChallengeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("FlagContexts");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcceptWithoutReview")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BloodBonusValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BloodBonus");

                    b.Property<int>("ContainerCountLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EndTimeUtc")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("end");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PracticeMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrivateKey")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartTimeUtc")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("start");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamMemberCountLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("WriteupDeadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("WriteupNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WriteupRequired")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GZCTF.Models.Data.GameChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AttachmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CPUCount")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeadlineUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("Difficulty")
                        .HasColumnType("REAL");

                    b.Property<bool>("DisableBloodBonus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableTrafficCapture")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExposePort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagTemplate")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hints")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MemoryLimit")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinScoreRate")
                        .HasColumnType("REAL");

                    b.Property<byte?>("NetworkMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0);

                    b.Property<int>("OriginalScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StorageLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubmissionLimit")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TestContainerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("GameId");

                    b.HasIndex("TestContainerId");

                    b.ToTable("GameChallenges");
                });

            modelBuilder.Entity("GZCTF.Models.Data.GameEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PublishTimeUtc")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("time");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("GameEvents");
                });

            modelBuilder.Entity("GZCTF.Models.Data.GameInstance", b =>
                {
                    b.Property<int>("ChallengeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipationId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ContainerId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FlagId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLoaded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastContainerOperation")
                        .HasColumnType("TEXT");

                    b.HasKey("ChallengeId", "ParticipationId");

                    b.HasIndex("ContainerId")
                        .IsUnique();

                    b.HasIndex("FlagId");

                    b.HasIndex("ParticipationId");

                    b.ToTable("GameInstances");
                });

            modelBuilder.Entity("GZCTF.Models.Data.GameNotice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PublishTimeUtc")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("time");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameNotices");
                });

            modelBuilder.Entity("GZCTF.Models.Data.LocalFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("ReferenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UploadTimeUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Hash");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("GZCTF.Models.Data.LogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Logger")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteIP")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Participation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DivisionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("WriteupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("GameId");

                    b.HasIndex("TeamId");

                    b.HasIndex("WriteupId");

                    b.HasIndex("TeamId", "GameId");

                    b.ToTable("Participations");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdateTimeUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("TEXT");

                    b.Property<int>("ChallengeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SubmitTimeUtc")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("time");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("GameId");

                    b.HasIndex("ParticipationId");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "ChallengeId", "GameId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasMaxLength(72)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CaptainId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteToken")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Locked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CaptainId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("GZCTF.Models.Data.UserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExerciseVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSignedInUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastVisitedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RegisterTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("StdNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GZCTF.Models.Data.UserParticipation", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "TeamId", "UserId");

                    b.HasIndex("ParticipationId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique();

                    b.ToTable("UserParticipations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TeamUserInfo", b =>
                {
                    b.Property<Guid>("MembersId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MembersId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("TeamUserInfo");
                });

            modelBuilder.Entity("GZCTF.Models.Data.ApiToken", b =>
                {
                    b.HasOne("GZCTF.Models.Data.UserInfo", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Attachment", b =>
                {
                    b.HasOne("GZCTF.Models.Data.LocalFile", "LocalFile")
                        .WithMany()
                        .HasForeignKey("LocalFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LocalFile");
                });

            modelBuilder.Entity("GZCTF.Models.Data.CheatInfo", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Participation", "SourceTeam")
                        .WithMany()
                        .HasForeignKey("SourceTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Participation", "SubmitTeam")
                        .WithMany()
                        .HasForeignKey("SubmitTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("SourceTeam");

                    b.Navigation("Submission");

                    b.Navigation("SubmitTeam");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Cyctf.Award", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Cyctf.GameExtension", "GameExtension")
                        .WithMany("Awards")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameExtension");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Cyctf.DivisionExtension", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Division", "Division")
                        .WithOne()
                        .HasForeignKey("GZCTF.Models.Data.Cyctf.DivisionExtension", "DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Cyctf.GameExtension", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Game", "Game")
                        .WithOne()
                        .HasForeignKey("GZCTF.Models.Data.Cyctf.GameExtension", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Cyctf.Registration", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.UserInfo", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GZCTF.Models.Data.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Game");

                    b.Navigation("Reviewer");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Cyctf.Sponsor", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Cyctf.GameExtension", "GameExtension")
                        .WithMany("Sponsors")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameExtension");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Division", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Game", "Game")
                        .WithMany("Divisions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GZCTF.Models.Data.DivisionChallengeConfig", b =>
                {
                    b.HasOne("GZCTF.Models.Data.GameChallenge", "Challenge")
                        .WithMany("DivisionConfigs")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Division", "Division")
                        .WithMany("ChallengeConfigs")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("Division");
                });

            modelBuilder.Entity("GZCTF.Models.Data.ExerciseChallenge", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GZCTF.Models.Data.Container", "TestContainer")
                        .WithMany()
                        .HasForeignKey("TestContainerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Attachment");

                    b.Navigation("TestContainer");
                });

            modelBuilder.Entity("GZCTF.Models.Data.ExerciseDependency", b =>
                {
                    b.HasOne("GZCTF.Models.Data.ExerciseChallenge", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.ExerciseChallenge", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("GZCTF.Models.Data.ExerciseInstance", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Container", "Container")
                        .WithOne("ExerciseInstance")
                        .HasForeignKey("GZCTF.Models.Data.ExerciseInstance", "ContainerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GZCTF.Models.Data.ExerciseChallenge", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.FlagContext", "FlagContext")
                        .WithMany()
                        .HasForeignKey("FlagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GZCTF.Models.Data.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");

                    b.Navigation("Exercise");

                    b.Navigation("FlagContext");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GZCTF.Models.Data.FirstSolve", b =>
                {
                    b.HasOne("GZCTF.Models.Data.GameChallenge", "Challenge")
                        .WithMany("FirstSolves")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Participation", "Participation")
                        .WithMany("FirstSolves")
                        .HasForeignKey("ParticipationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("Participation");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("GZCTF.Models.Data.FlagContext", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GZCTF.Models.Data.GameChallenge", "Challenge")
                        .WithMany("Flags")
                        .HasForeignKey("ChallengeId");

                    b.HasOne("GZCTF.Models.Data.ExerciseChallenge", "Exercise")
                        .WithMany("Flags")
                        .HasForeignKey("ExerciseId");

                    b.Navigation("Attachment");

                    b.Navigation("Challenge");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("GZCTF.Models.Data.GameChallenge", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GZCTF.Models.Data.Game", "Game")
                        .WithMany("Challenges")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Container", "TestContainer")
                        .WithMany()
                        .HasForeignKey("TestContainerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Attachment");

                    b.Navigation("Game");

                    b.Navigation("TestContainer");
                });

            modelBuilder.Entity("GZCTF.Models.Data.GameEvent", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Game", "Game")
                        .WithMany("GameEvents")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Game");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GZCTF.Models.Data.GameInstance", b =>
                {
                    b.HasOne("GZCTF.Models.Data.GameChallenge", "Challenge")
                        .WithMany("Instances")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Container", "Container")
                        .WithOne("GameInstance")
                        .HasForeignKey("GZCTF.Models.Data.GameInstance", "ContainerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GZCTF.Models.Data.FlagContext", "FlagContext")
                        .WithMany()
                        .HasForeignKey("FlagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GZCTF.Models.Data.Participation", "Participation")
                        .WithMany("Instances")
                        .HasForeignKey("ParticipationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("Container");

                    b.Navigation("FlagContext");

                    b.Navigation("Participation");
                });

            modelBuilder.Entity("GZCTF.Models.Data.GameNotice", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Game", "Game")
                        .WithMany("GameNotices")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Participation", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GZCTF.Models.Data.Game", "Game")
                        .WithMany("Participations")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Team", "Team")
                        .WithMany("Participations")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.LocalFile", "Writeup")
                        .WithMany()
                        .HasForeignKey("WriteupId");

                    b.Navigation("Division");

                    b.Navigation("Game");

                    b.Navigation("Team");

                    b.Navigation("Writeup");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Post", b =>
                {
                    b.HasOne("GZCTF.Models.Data.UserInfo", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Submission", b =>
                {
                    b.HasOne("GZCTF.Models.Data.GameChallenge", "GameChallenge")
                        .WithMany("Submissions")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Game", "Game")
                        .WithMany("Submissions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Participation", "Participation")
                        .WithMany("Submissions")
                        .HasForeignKey("ParticipationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.UserInfo", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Game");

                    b.Navigation("GameChallenge");

                    b.Navigation("Participation");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Team", b =>
                {
                    b.HasOne("GZCTF.Models.Data.UserInfo", "Captain")
                        .WithMany()
                        .HasForeignKey("CaptainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Captain");
                });

            modelBuilder.Entity("GZCTF.Models.Data.UserParticipation", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Participation", "Participation")
                        .WithMany("Members")
                        .HasForeignKey("ParticipationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Participation");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GZCTF.Models.Data.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GZCTF.Models.Data.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GZCTF.Models.Data.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamUserInfo", b =>
                {
                    b.HasOne("GZCTF.Models.Data.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GZCTF.Models.Data.Container", b =>
                {
                    b.Navigation("ExerciseInstance");

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Cyctf.GameExtension", b =>
                {
                    b.Navigation("Awards");

                    b.Navigation("Sponsors");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Division", b =>
                {
                    b.Navigation("ChallengeConfigs");
                });

            modelBuilder.Entity("GZCTF.Models.Data.ExerciseChallenge", b =>
                {
                    b.Navigation("Flags");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Game", b =>
                {
                    b.Navigation("Challenges");

                    b.Navigation("Divisions");

                    b.Navigation("GameEvents");

                    b.Navigation("GameNotices");

                    b.Navigation("Participations");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("GZCTF.Models.Data.GameChallenge", b =>
                {
                    b.Navigation("DivisionConfigs");

                    b.Navigation("FirstSolves");

                    b.Navigation("Flags");

                    b.Navigation("Instances");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Participation", b =>
                {
                    b.Navigation("FirstSolves");

                    b.Navigation("Instances");

                    b.Navigation("Members");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Team", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("GZCTF.Models.Data.UserInfo", b =>
                {
                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
