// <auto-generated />
using System;
using GZCTF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GZCTF.Migrations.MySQL
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240403180609_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GZCTF.Models.Data.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LocalFileId")
                        .HasColumnType("int");

                    b.Property<string>("RemoteUrl")
                        .HasColumnType("longtext");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("LocalFileId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("GZCTF.Models.Data.CheatInfo", b =>
                {
                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("SourceTeamId")
                        .HasColumnType("int");

                    b.Property<int>("SubmitTeamId")
                        .HasColumnType("int");

                    b.HasKey("SubmissionId");

                    b.HasIndex("GameId");

                    b.HasIndex("SourceTeamId");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.HasIndex("SubmitTeamId");

                    b.ToTable("CheatInfo");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Config", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("ConfigKey");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Container", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ExerciseInstanceId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ExpectStopAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GameInstanceId")
                        .HasColumnType("int");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsProxy")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("PublicIP")
                        .HasColumnType("longtext");

                    b.Property<int?>("PublicPort")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseInstanceId")
                        .IsUnique();

                    b.HasIndex("GameInstanceId")
                        .IsUnique();

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("GZCTF.Models.Data.ExerciseChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcceptedCount")
                        .HasColumnType("int");

                    b.Property<int?>("AttachmentId")
                        .HasColumnType("int");

                    b.Property<int?>("CPUCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("char(36)");

                    b.Property<int?>("ContainerExposePort")
                        .HasColumnType("int");

                    b.Property<string>("ContainerImage")
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Credit")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte>("Difficulty")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext");

                    b.Property<string>("FlagTemplate")
                        .HasColumnType("longtext");

                    b.Property<string>("Hints")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MemoryLimit")
                        .HasColumnType("int");

                    b.Property<int?>("StorageLimit")
                        .HasColumnType("int");

                    b.Property<int>("SubmissionCount")
                        .HasColumnType("int");

                    b.Property<byte>("Tag")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TestContainerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("TestContainerId");

                    b.ToTable("ExerciseChallenges");
                });

            modelBuilder.Entity("GZCTF.Models.Data.ExerciseDependency", b =>
                {
                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<int>("TargetId")
                        .HasColumnType("int");

                    b.HasKey("SourceId", "TargetId");

                    b.HasIndex("SourceId");

                    b.HasIndex("TargetId");

                    b.ToTable("ExerciseDependencies");
                });

            modelBuilder.Entity("GZCTF.Models.Data.ExerciseInstance", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ContainerId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("FlagId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLoaded")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSolved")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("LastContainerOperation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("SolveTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "ExerciseId");

                    b.HasIndex("ContainerId")
                        .IsUnique();

                    b.HasIndex("ExerciseId");

                    b.HasIndex("FlagId");

                    b.HasIndex("UserId");

                    b.ToTable("ExerciseInstances");
                });

            modelBuilder.Entity("GZCTF.Models.Data.FlagContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttachmentId")
                        .HasColumnType("int");

                    b.Property<int?>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("FlagContexts");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcceptWithoutReview")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("BloodBonusValue")
                        .HasColumnType("bigint")
                        .HasColumnName("BloodBonus");

                    b.Property<int>("ContainerCountLimit")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("EndTimeUtc")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "end");

                    b.Property<bool>("Hidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("InviteCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Organizations")
                        .HasColumnType("longtext");

                    b.Property<string>("PosterHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("PracticeMode")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PrivateKey")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)");

                    b.Property<DateTimeOffset>("StartTimeUtc")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "start");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TeamMemberCountLimit")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("WriteupDeadline")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WriteupNote")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("WriteupRequired")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GZCTF.Models.Data.GameChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcceptedCount")
                        .HasColumnType("int");

                    b.Property<int?>("AttachmentId")
                        .HasColumnType("int");

                    b.Property<int?>("CPUCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("char(36)");

                    b.Property<int?>("ContainerExposePort")
                        .HasColumnType("int");

                    b.Property<string>("ContainerImage")
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Difficulty")
                        .HasColumnType("double");

                    b.Property<bool>("EnableTrafficCapture")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext");

                    b.Property<string>("FlagTemplate")
                        .HasColumnType("longtext");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Hints")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MemoryLimit")
                        .HasColumnType("int");

                    b.Property<double>("MinScoreRate")
                        .HasColumnType("double");

                    b.Property<int>("OriginalScore")
                        .HasColumnType("int");

                    b.Property<int?>("StorageLimit")
                        .HasColumnType("int");

                    b.Property<int>("SubmissionCount")
                        .HasColumnType("int");

                    b.Property<byte>("Tag")
                        .HasColumnType("tinyint unsigned");

                    b.Property<Guid?>("TestContainerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("GameId");

                    b.HasIndex("TestContainerId");

                    b.ToTable("GameChallenges");
                });

            modelBuilder.Entity("GZCTF.Models.Data.GameEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("PublishTimeUtc")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "time");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("GameEvents");
                });

            modelBuilder.Entity("GZCTF.Models.Data.GameInstance", b =>
                {
                    b.Property<int>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipationId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ContainerId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("FlagId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLoaded")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSolved")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("LastContainerOperation")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ChallengeId", "ParticipationId");

                    b.HasIndex("ContainerId")
                        .IsUnique();

                    b.HasIndex("FlagId");

                    b.HasIndex("ParticipationId");

                    b.ToTable("GameInstances");
                });

            modelBuilder.Entity("GZCTF.Models.Data.GameNotice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("PublishTimeUtc")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "time");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameNotices");
                });

            modelBuilder.Entity("GZCTF.Models.Data.LocalFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("ReferenceCount")
                        .HasColumnType("int unsigned");

                    b.Property<DateTimeOffset>("UploadTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Hash");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("GZCTF.Models.Data.LogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Exception")
                        .HasColumnType("longtext");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Logger")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RemoteIP")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTimeOffset>("TimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Participation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Organization")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("WriteupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TeamId");

                    b.HasIndex("WriteupId");

                    b.HasIndex("TeamId", "GameId");

                    b.ToTable("Participations");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdateTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)");

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("SubmitTimeUtc")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "time");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("GameId");

                    b.HasIndex("ParticipationId");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "ChallengeId", "GameId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Bio")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("CaptainId")
                        .HasColumnType("char(36)");

                    b.Property<string>("InviteToken")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("Locked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("CaptainId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("GZCTF.Models.Data.UserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ExerciseVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("LastSignedInUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("LastVisitedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<DateTimeOffset>("RegisterTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("StdNumber")
                        .IsRequired()
                        .HasMaxLength(31)
                        .HasColumnType("varchar(31)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GZCTF.Models.Data.UserParticipation", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ParticipationId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "TeamId", "UserId");

                    b.HasIndex("ParticipationId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique();

                    b.ToTable("UserParticipations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("longtext");

                    b.Property<string>("Xml")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TeamUserInfo", b =>
                {
                    b.Property<Guid>("MembersId")
                        .HasColumnType("char(36)");

                    b.Property<int>("TeamsId")
                        .HasColumnType("int");

                    b.HasKey("MembersId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("TeamUserInfo");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Attachment", b =>
                {
                    b.HasOne("GZCTF.Models.Data.LocalFile", "LocalFile")
                        .WithMany()
                        .HasForeignKey("LocalFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LocalFile");
                });

            modelBuilder.Entity("GZCTF.Models.Data.CheatInfo", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Participation", "SourceTeam")
                        .WithMany()
                        .HasForeignKey("SourceTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Participation", "SubmitTeam")
                        .WithMany()
                        .HasForeignKey("SubmitTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("SourceTeam");

                    b.Navigation("Submission");

                    b.Navigation("SubmitTeam");
                });

            modelBuilder.Entity("GZCTF.Models.Data.ExerciseChallenge", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GZCTF.Models.Data.Container", "TestContainer")
                        .WithMany()
                        .HasForeignKey("TestContainerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Attachment");

                    b.Navigation("TestContainer");
                });

            modelBuilder.Entity("GZCTF.Models.Data.ExerciseDependency", b =>
                {
                    b.HasOne("GZCTF.Models.Data.ExerciseChallenge", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.ExerciseChallenge", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("GZCTF.Models.Data.ExerciseInstance", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Container", "Container")
                        .WithOne("ExerciseInstance")
                        .HasForeignKey("GZCTF.Models.Data.ExerciseInstance", "ContainerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GZCTF.Models.Data.ExerciseChallenge", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.FlagContext", "FlagContext")
                        .WithMany()
                        .HasForeignKey("FlagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GZCTF.Models.Data.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");

                    b.Navigation("Exercise");

                    b.Navigation("FlagContext");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GZCTF.Models.Data.FlagContext", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GZCTF.Models.Data.GameChallenge", "Challenge")
                        .WithMany("Flags")
                        .HasForeignKey("ChallengeId");

                    b.HasOne("GZCTF.Models.Data.ExerciseChallenge", "Exercise")
                        .WithMany("Flags")
                        .HasForeignKey("ExerciseId");

                    b.Navigation("Attachment");

                    b.Navigation("Challenge");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("GZCTF.Models.Data.GameChallenge", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GZCTF.Models.Data.Game", "Game")
                        .WithMany("Challenges")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Container", "TestContainer")
                        .WithMany()
                        .HasForeignKey("TestContainerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Attachment");

                    b.Navigation("Game");

                    b.Navigation("TestContainer");
                });

            modelBuilder.Entity("GZCTF.Models.Data.GameEvent", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Game", "Game")
                        .WithMany("GameEvents")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Game");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GZCTF.Models.Data.GameInstance", b =>
                {
                    b.HasOne("GZCTF.Models.Data.GameChallenge", "Challenge")
                        .WithMany("Instances")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Container", "Container")
                        .WithOne("GameInstance")
                        .HasForeignKey("GZCTF.Models.Data.GameInstance", "ContainerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GZCTF.Models.Data.FlagContext", "FlagContext")
                        .WithMany()
                        .HasForeignKey("FlagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GZCTF.Models.Data.Participation", "Participation")
                        .WithMany("Instances")
                        .HasForeignKey("ParticipationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("Container");

                    b.Navigation("FlagContext");

                    b.Navigation("Participation");
                });

            modelBuilder.Entity("GZCTF.Models.Data.GameNotice", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Game", "Game")
                        .WithMany("GameNotices")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Participation", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Game", "Game")
                        .WithMany("Participations")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Team", "Team")
                        .WithMany("Participations")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.LocalFile", "Writeup")
                        .WithMany()
                        .HasForeignKey("WriteupId");

                    b.Navigation("Game");

                    b.Navigation("Team");

                    b.Navigation("Writeup");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Post", b =>
                {
                    b.HasOne("GZCTF.Models.Data.UserInfo", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Submission", b =>
                {
                    b.HasOne("GZCTF.Models.Data.GameChallenge", "GameChallenge")
                        .WithMany("Submissions")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Game", "Game")
                        .WithMany("Submissions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Participation", "Participation")
                        .WithMany("Submissions")
                        .HasForeignKey("ParticipationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.UserInfo", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Game");

                    b.Navigation("GameChallenge");

                    b.Navigation("Participation");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Team", b =>
                {
                    b.HasOne("GZCTF.Models.Data.UserInfo", "Captain")
                        .WithMany()
                        .HasForeignKey("CaptainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Captain");
                });

            modelBuilder.Entity("GZCTF.Models.Data.UserParticipation", b =>
                {
                    b.HasOne("GZCTF.Models.Data.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Participation", "Participation")
                        .WithMany("Members")
                        .HasForeignKey("ParticipationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Participation");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GZCTF.Models.Data.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GZCTF.Models.Data.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GZCTF.Models.Data.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamUserInfo", b =>
                {
                    b.HasOne("GZCTF.Models.Data.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GZCTF.Models.Data.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GZCTF.Models.Data.Container", b =>
                {
                    b.Navigation("ExerciseInstance");

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("GZCTF.Models.Data.ExerciseChallenge", b =>
                {
                    b.Navigation("Flags");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Game", b =>
                {
                    b.Navigation("Challenges");

                    b.Navigation("GameEvents");

                    b.Navigation("GameNotices");

                    b.Navigation("Participations");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("GZCTF.Models.Data.GameChallenge", b =>
                {
                    b.Navigation("Flags");

                    b.Navigation("Instances");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Participation", b =>
                {
                    b.Navigation("Instances");

                    b.Navigation("Members");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("GZCTF.Models.Data.Team", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("GZCTF.Models.Data.UserInfo", b =>
                {
                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
